In [22]:
#import library
import pandas as pd
import collections
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download the punkt tokenizer if not already downloaded
nltk.download('punkt')
# Download the stopwords if not already downloaded
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Ali\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ali\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [23]:
# datafeame of Primary data
df = pd.read_csv("train_data.csv")
num_of_rows = len(df)
df

,Unnamed: 0,textID,text,label,label_text
0,14951,7627d7ca56,Hi : Found you through . i am indeed a pigment...,1,neutral
1,6051,7527ed21ee,I`m so unhappy being here. I hate it. It`s aff...,0,negative
2,12712,2f6d9d1419,#stackeoverflow http://bit.ly/13Nfk1,1,neutral
3,2930,9afe83da6a,I`m completely exhausted thanks to yesterday. ...,0,negative
4,2174,322b61740c,"90 degrees, gross skies, and thunderstorms...p...",2,positive
...,...,...,...,...,...
19780,11964,96674184d6,_X sorry about that.,0,negative
19781,21575,14ba250631,@_Bella_Cullen13 posted and its good,2,positive
19782,5390,ae19d98db6,:: holy kraut. I canNOT stay up this late. But...,0,negative
19783,860,e9fdfb3211,with your bicycle?,1,neutral
19784,15795,4b9f6d5ddb,Having a good...no great day already & Dr.Mira...,2,positive

In [24]:
#phase1
# preprocess data into clean data
def preprocess(text):
    if isinstance(text, str):
        word_list = word_tokenize(text)
        stop_words = set(stopwords.words('english'))
        filtered_word_list = [word.lower() for word in word_list if word.lower() not in stop_words and len(word) > 2]
        
        return filtered_word_list
    
    return []

In [26]:
#phase2

# iterate text columns from df and using preprocess function
total_words = list()
positive_words = list()
negative_words = list()
neutral_words = list()

for i in range(num_of_rows):
    text_to_process = df["text"][i]
    result = list(preprocess(text_to_process))
    total_words.extend(result)
    
    #convert words into positive and negative and neutral categories
    if df.iloc[i]['label_text'] == 'positive':
        positive_words.extend(result)
        
    elif df.iloc[i]['label_text'] == 'negative':
        negative_words.extend(result)
        
    if df.iloc[i]['label_text'] == 'neutral':
        neutral_words.extend(result)

# Find the number of repetitions of words
count_data_total = collections.Counter(total_words)
count_data_positive = collections.Counter(positive_words)
count_data_negative = collections.Counter(negative_words)
count_data_neutral = collections.Counter(neutral_words)

#create dataframe with 4 columns words, positive , negative, neutral
words = count_data_total.keys()
pos = [count_data_positive[i] for i in words]
neg = [count_data_negative[i] for i in words]
neutral = [count_data_neutral[i] for i in words]

#show df
dict = {'word': words, 'positive': pos, 'negative': neg, 'neutral':neutral} 
df1 = pd.DataFrame(dict)
df1.head(50)

               word  positive  negative  neutral
0             found        32        35       49
1            indeed        12         4        4
2           pigment         0         0        1
3       imagination         2         0        1
4           unhappy         0         5        0
5              hate         5       193       46
6         affecting         0         1        0
7        everything        31        25       36
8     relationships         0         3        0
9            people        72        94      102
10      personality         2         1        1
11         attitude         1         1        1
12              ...       779       908     1061
13   stackeoverflow         0         0        1
14             http       301       171      413
15  //bit.ly/13nfk1         0         0        1
16       completely         7        14        8
17        exhausted         1        13        6
18           thanks       402        18       63
19        yesterday        38        37       39
20             home       145       143      254
21              yet        53        42       72
22          degrees         3         5        3
23            gross         2         3        4
24            skies         2         1        0
25    thunderstorms         1         1        0
26          perfect        36         8        9
27            match         6         5        7
28             mood        12        17       12
29              lol       246       111      353
30             cant        39        90       58
31          believe        33        37       35
32             stay        22        16       32
33             late        27        48       50
34            .....        24        48       35
35           waking         7        12        8
36             work       184       290      361
37          t-minus         0         2        1
38           4hours         0         1        0
39           _nobel         0         0        1
40              omg        40        70       45
41              mom       136        31       54
42           called        16        22       29
43              hes         3         4       11
44             gone        22        46       46
45          engaged         1         1        0
46              may        73        45       62
47              1st        10         9       14
48             best       159        19       51
49              guy        24        16       27